### ISSUE TITLE
Deploy notification server to AWS Lambda

### ISSUE THREAD

**Issue by siyeonSon** [depromeet/street-drop-server#300]
## DESCRIPTION
In order to reduce costs associated with EC2, we are introducing the AWS Lambda serverless computing service.
We minimize dependencies to facilitate a potential transition back to EC2 in the future.

### TODO
Deploy notification server to AWS Lambda

**Comment by seonghun-dev** [comment]
Change AoT compiler to Aot if you need to run as fast as serverless, or JIT compiler to Aot because it is more suitable for long-term application retention server environments
![img1 daumcdn](https://github.com/depromeet/street-drop-server/assets/80201773/1b2e4530-7d54-4ab6-9c1f-b61d9f32341a)

**Comment by seonghun-dev** [comment]
배치서버랑 알림서버가 통합되어 AWS LightSails에서 운영됨
