### ISSUE TITLE
Add Error Monitoring to Discord Channel

### ISSUE THREAD

**Issue by yunyoung1819** [depromeet/street-drop-server#412]
### DESCRIPTION
- Add Error Monitoring to Discord Channel

### TODO
- Add Error Monitoring to Discord Channel 
- Add Slow Query Monitoring to Discord Channel 

### TEST
- JUnit

### REFERENCE
- Related:

**Comment by seonghun-dev** [comment]
- 디스코드 웹훅알림 반응속도가 느려서 슬랙으로 유지
